/**
 * @author TimTsang
 * @date 2014年7月18日
 * @CopyRight 2014 Topview Inc
 * @version v1.0
 * @description 字段映射表
 */
var VLMAP = {
	"and" : "且",
	"or" : "或",

	"ZA_LYT_LKBH" : "旅客编号",
	"ZA_LYT_TH" : "团号",
	"ZA_LYT_XM" : "姓名",
	"ZA_LYT_XMPY" : "姓名拼音",
	"ZA_LYT_XB" : "性别",
	"ZA_LYT_MZ" : "民族",
	"ZA_LYT_CSRQ" : "出生日期",
	"ZA_LYT_ZJLX" : "证件类型",
	"ZA_LYT_ZJHM" : "证件号码",
	"ZA_LYT_XZQH" : "常住行政区划",
	"ZA_LYT_CZDZ" : "常住地址",
	"ZA_LYT_LGMC" : "旅馆名称",
	"ZA_LYT_LGBH" : "旅馆编号",
	"ZA_LYT_LGDZ" : "旅馆地址",
	"ZA_LYT_RZFH" : "入住房号",
	"ZA_LYT_RZSJ" : "旅客入住时间",
	"ZA_LYT_RZDBRY" : "入住当班人员",
	"ZA_LYT_TFSJ" : "退房时间",
	"ZA_LYT_TFDBRY" : "退房当班人员",
	"ZA_LYT_XYKLX" : "信用卡类型",
	"ZA_LYT_XYKHM" : "信用卡号码",
	"ZA_LYT_ZPCD" : "照片长度",
	"ZA_LYT_FSSJ" : "发送时间",
	"ZA_LYT_JSSJ" : "接收时间",
	"ZA_LYT_RKSJ" : "地市入库时间",
	"ZA_LYT_RZXH" : "入住序号",
	"ZA_LYT_HTRKSJ" : "后台入库时间",
	"ZA_LYT_GXSJ" : "地市更新时间",

	"FLIGHT" : "航班号",
	"OFFDAY" : "航班日期",
	"OFFDAY_C" : "航班日期_c",
	"STRT" : "始发港",
	"DEST" : "到达港",
	"DEPTTM" : "始发时间",
	"ARVETM" : "到达时间",
	"CCTIME" : "CC时间",
	"CHINESE_NAME" : "中文名",
	"ENGLISH_NAME" : "英文名",
	"FOID" : "证件号码",
	"ASCR_CODE" : "户籍代码",
	"ASCR_NAME" : "户籍地址",
	"PNR" : "订票号",
	"BDNO" : "登机牌号",
	"SEAT" : "座位号",
	"CLASS" : "舱位",
	"NATION" : "国籍",
	"SEX" : "性别",
	"BORTH" : "出生日期",
	"PHONE" : "联系电话",
	"BAGUNIT" : "行李件数",
	"BAGINFO" : "行李信息",

	"SALE_TIME" : "售票时间",
	"OFFICE_NO" : "售票点",
	"WINDOW_NO" : "售票窗口",
	"TICKET_NO" : "车票编号",
	"BOARD_TRAIN_CODE" : "车次",
	"TRAIN_DATE" : "乘车日期",
	"START_TIME" : "发车时间",
	"COACH_NO" : "车厢号",
	"SEAT_NO" : "座位号",
	"FROM_STATION_NAME" : "始发站",
	"TO_STATION_NAME" : "到达站",
	"ID_NO" : "证件号码",
	"ID_NAME" : "姓名",
	"YBZJ" : "原表主键",
	"XMTYIN" : "姓名同音",
	"XMTYUN" : "姓名同韵",
	"JLRKSJ" : "记录入库时间",
	"JLXGSJ" : "记录修改时间",
	"RYWYH" : "RYWYH",

	"instr" : "包含",
	"endWith" : "以...结束",
	"isNotNull" : "不为空",
	"isNull" : "为空",
	"starWith" : "以...开始",
	"between" : "在...之间",
	"=" : "等于",
	"GreaterThan" : "大于",
	"LessThan" : "小于",
	"NotEqual" : "不等于",
	"GreaterThanOrEqualTo" : "大于等于",
	"LessThanOrEqualTo" : "小于等于"
	,
};
